// This file was generated by a custom prisma generator, do not edit manually.
export const OrderStatus = {
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  OUT_OF_STOCK: "OUT_OF_STOCK",
} as const;

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export const Gender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  OTHER: "OTHER",
} as const;

export type Gender = (typeof Gender)[keyof typeof Gender];

export const DoctorSpecialization = {
  CARDIOLOGIST: "CARDIOLOGIST",
  DERMATOLOGIST: "DERMATOLOGIST",
  GYNECOLOGIST: "GYNECOLOGIST",
  NEUROLOGIST: "NEUROLOGIST",
  ORTHOPEDIC: "ORTHOPEDIC",
  PEDIATRICIAN: "PEDIATRICIAN",
  PSYCHIATRIST: "PSYCHIATRIST",
  UROLOGIST: "UROLOGIST",
} as const;

export type DoctorSpecialization = (typeof DoctorSpecialization)[keyof typeof DoctorSpecialization];

export const DoctorQualification = {
  MD: "MD",
  MDDM: "MDDM",
  DSO: "DSO",
  GENERAL_SURGEON: "GENERAL_SURGEON",
  GENERAL_MEDICINE: "GENERAL_MEDICINE",
} as const;

export type DoctorQualification = (typeof DoctorQualification)[keyof typeof DoctorQualification];

export const PaymentMethod = {
  CREDIT_CARD: "CREDIT_CARD",
  DEBIT_CARD: "DEBIT_CARD",
  CASH: "CASH",
} as const;

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod];

export const MedicationType = {
  CAPSULE: "CAPSULE",
  TABLET: "TABLET",
  SYRUP: "SYRUP",
} as const;

export type MedicationType = (typeof MedicationType)[keyof typeof MedicationType];

export const MedicationUnit = {
  MG: "MG",
  ML: "ML",
} as const;

export type MedicationUnit = (typeof MedicationUnit)[keyof typeof MedicationUnit];
